# Default values for demo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: quay.io/jknurek/python-redis-example
  tag: 0.1.1
  pullPolicy: IfNotPresent
service:
  name: flask
  type: LoadBalancer
  externalPort: 80
  internalPort: 5000

resources: {}

redis:
  usePassword: false